config/routes.rb
Rails.application.routes.draw do
  resources :posts

  post '/posts/unfollow', to: 'posts#unfollow'
  post '/posts/retweet', to: 'posts#retweet'
  post '/posts/favorite', to: 'posts#favorite'
  post '/posts/unfavorite', to: 'posts#unfavorite'
  get '/retweeted', to: 'dashboard#retweeted'
  get 'mentions', to: 'dashboard#mentions'
  get '/feed', to: 'dashboard#feed'
  # get '/posts', to: 'posts#index'
  get '/auth/twitter', as: :login

  get  '/dashboard', to: 'dashboard#show'
  root 'home#show'

  delete '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/sessiontest', to: 'sessions#create'
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :provider, :uid, :name

  def self.find_or_create_by_auth(auth)
    return if invalid_attributes?(auth)
    user = User.find_or_create_by(provider: auth['provider'], uid: auth['uid'])
    user.name = auth['info']['name']
    user.bio = auth['info']['description']
    user.image_url = auth['info']['image'].sub("_normal", "")
    user.token = auth['credentials']['token']
    user.secret = auth['credentials']['secret']
    user.save
    user
  end

  def self.invalid_attributes?(auth)
    auth["provider"] != 'twitter' || auth["uid"].nil? ? true : false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :img_url

  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def img_url(tweet)
    data = JSON.parse(tweet.to_json).to_h
    if data["quoted_status"].nil?
      url = data["user"]["profile_image_url_https"]
    else
      url = data["quoted_status"]["user"]["profile_image_url_https"]
    end
    url
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    service = TwitterService.new(current_user)
    @followers ||= service.followers.count
    @friends ||= service.friends.count
  end

  def feed
    @feed = TwitterService.new(current_user).user_feed
  end

  def mentions
    @feed = TwitterService.new(current_user).user_mentions
  end

  def retweeted
    @feed = TwitterService.new(current_user).retweeted
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @tweets = TwitterService.new(current_user).user_tweets
  end

  def create
    TwitterService.new(current_user).tweet(params["q"])
    redirect_to dashboard_path
  end

  def retweet
    TwitterService.new(current_user).retweet(params[:id])
    respond_to do |format|
      format.html {redirect_to :back}
      format.js
    end
  end

  def favorite
    TwitterService.new(current_user).favorite(params[:id])
    respond_to do |format|
      format.html {redirect_to :back}
      format.js
    end
  end

  def unfavorite
    TwitterService.new(current_user).unfavorite(params[:id])
    respond_to do |format|
      format.html {redirect_to :back}
      format.js
    end
  end

  def unfollow
    TwitterService.new(current_user).unfollow(params[:id].to_i)
    respond_to do |format|
      format.html {redirect_to :back}
      format.js
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :omniath?, only: [:create]

  def new
  end

  def create
    @user = User.find_or_create_by_auth(request.env["omniauth.auth"])
    if @user
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      redirect_to root_path
    end
  end

  def destroy
    session.destroy
    redirect_to root_path
  end

  private

    def omniath?
      redirect_to root_path if request.env["omniauth.auth"].nil?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/feed.html.erb
<%= image_tag('bird.png', class: "bird") %>
<%= image_tag current_user.image_url, class: "img-circle img-thumbnail home-image" %>
<%= link_to "Logout", "/logout", class: "btn btn-lg btn-default btn-home fades2", method: :delete %>
<%= link_to "Dashboard", dashboard_path, class: "btn btn-lg btn-default btn-home fades2" %>

<div class="intro">
  <h1 class="home hi">Bird, bird, buuurd</h1>
  <h2 class="home bio"> Tweetin' friends... </h2>
</div>

<div class="pillar container">
  <div>
    <h2 class="header home">Your Feed</h2>
  </div>

  <% @feed.each_with_index do |tweet, i| %>
    <div class="row tweet-card  card<%=i%>">
      <%= image_tag img_url(tweet), class: "img-circle img-thumbnail tweet-image" %>
      <span> <%= auto_link(tweet.text, :html => { :target => '_blank' }) %> <br><br>
      <strong>- <%= tweet.user.name %></strong></span>
      <% if tweet.favorited? %>
        <%= link_to(image_tag("fullheart0.png"), posts_unfavorite_path(id: tweet.id), remote: true, class: "unfavorite", id: "unfavorite", method: :post, :"data-label" => "incard#{i}" ) %>
        <%= link_to(image_tag("fullheart.png"), posts_favorite_path(id: tweet.id), remote: true, class: "favorite", id: "favorite", method: :post, :"data-label" => "incard#{i}") %>
      <% else %>
        <%= link_to(image_tag("fullheart.png"), posts_favorite_path(id: tweet.id), remote: true, class: "favorite", id: "favorite", method: :post, :"data-label" => "incard#{i}") %>
        <%= link_to(image_tag("fullheart0.png"), posts_unfavorite_path(id: tweet.id), remote: true, class: "unfavorite hidden", id: "unfavorite", method: :post, :"data-label" => "incard#{i}") %>
      <% end %>
      <%= button_to "Retweet", posts_retweet_path(id: tweet.id), :remote => true, class: "btn btn-lg btn-default btn-home retweet" %>
      <%= button_to "Unfollow", posts_unfollow_path(id: tweet.user.id), :remote => true, class: "btn btn-lg btn-default btn-home unfollow" %>
    </div>
  <% end %>
</div>

app/views/dashboard/mentions.html.erb
<%= image_tag('bird.png', class: "bird") %>
<%= image_tag current_user.image_url, class: "img-circle img-thumbnail home-image" %>
<%= link_to "Logout", "/logout", class: "btn btn-lg btn-default btn-home fades1", method: :delete %>
<%= link_to "Dashboard", dashboard_path, class: "btn btn-lg btn-default btn-home fades2" %>

<div class="intro">
  <h1 class="home hi">Other Birds</h1>
</div>

<div class="pillar container">

  <div class="container-fluid container">
    <div class="col-md-8 intro">
      <h2 class="home bio">Singin 'bout you...</h2>
    </div>
  </div>

  <div>
    <h2 class="header home">You've been mentioned</h2>
  </div>

  <% @feed.each do |tweet| %>
    <div class="row tweet-card">
      <%= image_tag img_url(tweet), class: "img-circle img-thumbnail tweet-image" %>
      <span> <%= auto_link(tweet.text, :html => { :target => '_blank' }) %> <br> - <%= tweet.user.name %> </span>
    </div>
  <% end %>

</div>

app/views/dashboard/retweeted.html.erb
<%= image_tag('bird.png', class: "bird") %>
<%= image_tag current_user.image_url, class: "img-circle img-thumbnail home-image" %>
<%= link_to "Logout", "/logout", class: "btn btn-lg btn-default btn-home fades1", method: :delete %>
<%= link_to "Dashboard", dashboard_path, class: "btn btn-lg btn-default btn-home fades2" %>

<div class="intro">
  <h1 class="home hi">Your tweets have echoed</h1>
</div>

<div class="pillar container">

  <div class="container-fluid container">
    <div class="col-md-8 intro">
      <h2 class="home bio">They're singing your song...</h2>
    </div>
  </div>

  <div>
    <h2 class="header home">Retweets of/by You</h2>
  </div>

  <% @feed.each do |tweet| %>
    <div class="row tweet-card">
      <%= image_tag img_url(tweet), class: "img-circle img-thumbnail tweet-image" %>
      <span> <%= auto_link(tweet.text, :html => { :target => '_blank' }) %> <br> - <%= tweet.quoted_status.user.name %> </span>
    </div>
  <% end %>

</div>

app/views/dashboard/show.html.erb
<%= image_tag('bird.png', class: "bird") %>
<%= image_tag current_user.image_url, class: "img-circle img-thumbnail home-image" %>
<%= link_to "Logout", "/logout", class: "btn btn-lg btn-default btn-home fades1", method: :delete %>
<%= link_to "Dashboard", dashboard_path, class: "btn btn-lg btn-default btn-home fades2" %>
<h6 class="stats"> <%= @followers %> followers,</h6>
<h6 class="stats2"> following <%= @friends %> </h6>

<div class="container">
  <div class="intro">
    <h1 class="home hi">Hi, <%= current_user.name %></h1>
    <h2 class="home bio"> <%= current_user.bio %> </h2>
  </div>

  <div class="pillar container">
    <div>
      <h2 class="header home">Your Twitter Stats</h2>
    </div>
    <div class="row">
      <div class="col-6sm">
        <%= link_to "Timeline", "/feed", class: "btn btn-lg btn-default btn-dash" %>
        <%= link_to "Your Posts", posts_path, class: "btn btn-lg btn-default btn-dash" %>
      </div>
      <div class="row">
        <%= link_to "Mentions", '/mentions', class: "btn btn-lg btn-default btn-dash fades3" %>
        <%= link_to "Retweets", '/retweeted', class: "btn btn-lg btn-default btn-dash fades3" %>
      </div>
    </div>

    <div class="tweet-form">
      <%= form_tag('/posts', :method => "post") do %>
          <%= label_tag(:q, "Tweet:", class: "small-text") %>
          <%= text_field_tag(:q) %>
          <div><%= image_submit_tag('bird.png', class: "tweet-bird", id: "send-tweet") %></div>
      <% end -%>
    </div>
  </div>
</div>

app/views/home/show.html.erb
<%= image_tag('bird.png', class: "bird") %>
<!-- <%= image_tag('/assets/jamie.jpg', class: "about") %> -->
<div class="container-fluid container-home">
  <div class="circle-go"></div>
  <div class="circle-come"></div>
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <h1 class="home">TweetSpy</h1>
    <h2 class="home">You little songbird...</h2>
    <%= link_to "Login with Twitter", login_path, class: "btn btn-lg btn-default btn-home" %>
  </div>
  <div class="col-md-2"></div>
  <div class="circle2"></div>
  <div class="circle3"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApiCurious</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1"></head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/favorite.js.erb
$('target').html(" <%= escape_javascript() %> ")

app/views/posts/index.html.erb
<%= image_tag('bird.png', class: "bird") %>
<%= image_tag current_user.image_url, class: "img-circle img-thumbnail home-image" %>
<%= link_to "Logout", "/logout", class: "btn btn-lg btn-default btn-home fades1", method: :delete %>
<%= link_to "Dashboard", dashboard_path, class: "btn btn-lg btn-default btn-home fades2" %>
<!-- <%= link_to "Your Posts", posts_path, class: "btn btn-lg btn-default btn-home fades3" %> -->
<!-- <%= link_to "Timeline", "/feed", class: "btn btn-lg btn-default btn-home fades3" %> -->

<div class="container-fluid container">
  <div class="col-md-8 intro">
    <h1 class="home hi">The little songs</h1>
    <h2 class="home blurb">you have recently sung to the world...</h2>
  </div>
</div>

<div class="pillar container">
  <div>
    <h2 class="header home">Your Tweets</h2>
  </div>
  <% @tweets.each do |tweet| %>
    <div class="row tweet-card">
      <%= image_tag img_url(tweet), class: "img-circle img-thumbnail tweet-image" %>
      <span> <%= auto_link(tweet.text, :html => { :target => '_blank' }) %> </span>
    </div>
  <% end %>
</div>

app/views/posts/retweet.js.erb
// $('#retweet').click(function() {
//     $(this).hide();
// });
// $('a.button-next').click(function() {
//     $('.content').hide(); // To hide all other contents
//     $(".retweeted").show(); // Show the one content you want to display
// });